#!/bin/bash

echo "UniFi Network Exporter - GitHub Actions Secrets Setup"
echo "====================================================="
echo ""
echo "This script will help you set up the required secrets for the release workflow."
echo ""
echo "You'll need:"
echo "1. A Docker Hub account (https://hub.docker.com/)"
echo "2. A crates.io account with an API token (https://crates.io/me)"
echo "3. The GitHub CLI (gh) installed and authenticated"
echo ""
echo "First, copy .env.example to .env:"
echo ""
echo "  cp .env.example .env"
echo ""
echo "Then edit .env and fill in your actual values:"
echo ""
echo "  DOCKER_USERNAME=your-docker-username"
echo "  DOCKER_PASSWORD=your-docker-password" 
echo "  CRATES_IO_TOKEN=your-crates-io-token"
echo ""
echo "Finally, run:"
echo ""
echo "  make gh-secrets"
echo ""
echo "This will set the secrets in your GitHub repository."
echo ""
echo "Note: You'll need a different crates.io token than the one used for"
echo "the HomeWizard exporters since this is a different crate."